### ISSUE TITLE
Still have issues :/

### ISSUE THREAD

**Issue by Nechromanthys** [tomazas/ledcube8x8x8#7]
Hello,
i bought a cube, did the soldering, did quick test one row, 3 led permanently on, no blinking. I thought i mess with the soldering, i bought a second cube, still same problem.
I find out it is a common issue for non programmed chip, i ends up on this page.
I've managed to follow your guide and reprogrammed the chip, all looks exactly how you show, i did the 1st part with stc-isp-15xx-v6.86R software.
Although the one row quick test now blinks only 1st and 8th led, nothing else, on both kits, i've tried reprogramming with 2 different laptop, same result.
Please do you have any clue about what could be the cause?
Thanks and regards

**Comment by sjack214** [comment]
My chips are programed already but the big problem i had was that i used wire between the let Cube and the ice inplace of the plastic sticks that hold the Cube up now IT make beter contact and van test everything appart .sjack

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by tomazas** [comment]
> Hello,
> i bought a cube, did the soldering, did quick test one row, 3 led permanently on, no blinking. I thought i mess with the soldering, i bought a second cube, still same problem.
> I find out it is a common issue for non programmed chip, i ends up on this page.
> I've managed to follow your guide and reprogrammed the chip, all looks exactly how you show, i did the 1st part with stc-isp-15xx-v6.86R software.
> Although the one row quick test now blinks only 1st and 8th led, nothing else, on both kits, i've tried reprogramming with 2 different laptop, same result.
> Please do you have any clue about what could be the cause?
> Thanks and regards

There could be many different problems e.g.:
1. You incorrectly assembled the cubes, e.g. put the chips in reverse
2. The cube is different (other MCU chip, trace routing/connections)
3. Bad USB UART module or cable connections
4. other...

It's impossible to help without receiving all the details about the cube and what was done to it.
I'm afraid but I cannot help you unless you found an actual cause related to the code given in this Github repo.
