### ISSUE TITLE
Firmware LED mapping issues

### ISSUE THREAD

**Issue by Sliicy** [tomazas/ledcube8x8x8#9]
I'm having issues with the mapping of the cube LEDs.
Reproduction steps:
I successfully flash firmware/v2/ledcube8.hex.
After flashing, all the LEDs are on.
I run DotMatrix Java at 19200 Baud and successfully connect to the Cube.
I send the following packet, which turns all the LEDs OFF (this packet is supposed to turn them ON):
0xf2, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
![image](https://user-images.githubusercontent.com/23116873/127198259-122ca4b5-209f-4f13-9755-7327ecfdc6ee.png)
![Cube Off](https://user-images.githubusercontent.com/23116873/127345814-ff5d4791-1f3d-4ca3-ade3-a6d67c3aca0c.jpg)

### I kept experimenting with the packets, and found that they all light up on the same column:
![image](https://user-images.githubusercontent.com/23116873/127198376-835b97d6-3a92-49c2-878a-dfdf08823268.png)
![IMG_20210727_125810](https://user-images.githubusercontent.com/23116873/127198382-8b47451c-7366-4d4d-b340-262f64cff49b.jpg)

### Attempt 3:
![image](https://user-images.githubusercontent.com/23116873/127198412-1482e618-22a6-4ebc-93b7-67c775396c54.png)
![IMG_20210727_125901](https://user-images.githubusercontent.com/23116873/127198416-0a62fc53-e132-4d3b-8d29-b2ea06d7e549.jpg)

### Attempt 4:
![image](https://user-images.githubusercontent.com/23116873/127198471-bf8b69fb-f089-48e5-9a81-d422c770b913.png)
![IMG_20210727_125810](https://user-images.githubusercontent.com/23116873/127198382-8b47451c-7366-4d4d-b340-262f64cff49b.jpg)

### Attempt 5:
![image](https://user-images.githubusercontent.com/23116873/127198512-125e326a-3f67-484b-a6dc-908cb3da96bd.png)
![IMG_20210727_130002](https://user-images.githubusercontent.com/23116873/127198483-ed82faae-e076-4393-b93e-1c4966cdf112.jpg)

### Attempt 6:
![image](https://user-images.githubusercontent.com/23116873/127198560-be2e2c9f-6756-4af6-b189-934e6458f44a.png)
![IMG_20210727_130125](https://user-images.githubusercontent.com/23116873/127198524-4d369787-77fe-48e7-91ad-765a40986db7.jpg)

### Attempt 7:
![image](https://user-images.githubusercontent.com/23116873/127199300-91a7ba01-d126-45d1-bbe9-d2f72c8620dd.png)
![IMG_20210727_130155](https://user-images.githubusercontent.com/23116873/127198570-2409e593-76aa-45fb-916c-823e8c22cad7.jpg)

### Turning them all "Off":
![image](https://user-images.githubusercontent.com/23116873/127199687-71862141-4ed0-4bf8-a80a-de4253537cd9.png)
![Cube Lit](https://user-images.githubusercontent.com/23116873/127345881-e913ef11-0970-4de8-b5fb-fe1ceb40f9fd.jpg)

If it helps, I have both the schematic design and original firmware .hex file that the cube came with.
[4-Schematic Diagram.pdf](https://github.com/tomazas/ledcube8x8x8/files/6887520/4-Schematic.Diagram.pdf)

GitHub won't allow attaching the .hex file as a comment, so I might just perform a pull request if needed.
The SHA1sum of the .hex file is 8c4ec84be90ccda53cdd21a5898db66ac214aa05.

The Letoo 3D8 software program saves the files as a .gpro8 type:
![image](https://user-images.githubusercontent.com/23116873/127202295-fc6915d1-fd54-4e53-96a9-494a8fd528ba.png)

All these files were supplied via a link from the seller:
https://drive.google.com/file/d/1a62NuU_QtyUHD0oo4XSAAWj_dZoWQHCB

I also tried uploading the firmware/8X8X8X.hex file, which does show some animations, but ultimately, I think the firmware might need to be modified to support this motherboard.
![image](https://user-images.githubusercontent.com/23116873/127202142-fc6a0f72-0405-417c-8121-2a6085cfdbd4.png)

**Comment by tomazas** [comment]
The original cube has DIP parts while this one is completely SMT based. 
Meaning that connections and working behavior is somewhat different (you already experienced this).

The software/firmware does not support all kinds/ports/versions of LED cubes (incl. iCubeSmart 3D8S DIY). 
If you or someone is up for the challenge to adapt the firmware and test the code with this cube/hardware, then please go ahead.
Sorry, but I won't be able to help here.

**Comment by Sliicy** [comment]
Wouldn't the SMD/DIP depend on the LEDs soldered into the board? The board has printed on the back "DIP Led". Here's a close-up of the LEDs used:
![IMG_20210728_103509](https://user-images.githubusercontent.com/23116873/127341643-f9f4d6a7-c698-4fd1-b9b0-0d6d3ed01fba.jpg)
I thought that both my cube and this project use DIP.

Also, where would be a good place to start? Is the firmware/v2/888_v2.c file the only thing that needs modification (and then compilation) to get it to work? And do you know what commands were used to compile it from .c to .hex?

**Comment by Sliicy** [comment]
@tomazas after inspecting the board, it seems my Cube uses a 24.000MHz MCU (clock frequency = 23.962MHz), whereas the code uses 12MHz:
```c
    // init uart - 9600bps@12.000MHz MCU
    PCON &= 0x7F;       //Baudrate no doubled
    SCON = 0x50;        //8bit and variable baudrate, 1 stop __bit, no parity
    AUXR |= 0x04;       //BRT's clock is Fosc (1T)
    BRT = 0xD9;         //Set BRT's reload value
    AUXR |= 0x01;       //Use BRT as baudrate generator
    AUXR |= 0x10;       //BRT running
```

What would the above code look like if I wanted it to run at 24MHz? Also, what if I wanted it to run at 115200 Baud?
Maybe that might fix the issue?

MCU additional info:
```
H/W Option upgrade to:
  . Current system clock source is external crystal oscillator
  . Current clock frequency: 23.962MHz
  . Oscillator gain is HIGH
  . RESET pin behaves as reset pin
  . No low level detection on RESET2 pin
  . Power-on reset, use the extra power-on delay
  . Hardware do not enable Watch-Dog-Timer
  . Watch-Dog-Timer pre-scalar : 256
  . Watch-Dog-Timer stop count in idle mode
  . Program can modify the Watch-Dog-Timer scalar
  . Do not detect the level of P1.0 and P1.1 next download
  . Do not erase user EEPROM area at next download

  . MCU ID : D17EC59205195F
  . MCU type: STC12C5A60S2
  F/W version: 7.1.4I
```

**Comment by Sliicy** [comment]
I was successful in troubleshooting why this behavior is occurring!
By referencing the Datasheet (http://www.stcmicro.com/datasheet/STC12C5A60S2-en.pdf), and Schematics, I found that these 8 pins control each row of LEDs:
![image](https://user-images.githubusercontent.com/23116873/127619605-76eb73a8-62e5-4890-af7e-66ce5b683cd6.png)
![Port1](https://user-images.githubusercontent.com/23116873/127619647-8b379af1-a36e-4c07-80c4-113beb63a0e6.png)

By reading the Datasheet, there is a variable called "P1ASF" responsible for setting those 8 pins to either operate in analog or digital mode. My Cube is basically turning all 8 rows on, because P1ASF is set to 0x00 by default.
When I set P1ASF to 255, all the LEDs turn off.

Here are my findings:

```c
P1ASF = 0;   // All On
P1ASF = 255; // All off
P1ASF = 127; // Row 8 on (Top row)
P1ASF = 191; // Row 7 on
P1ASF = 223; // Row 6 on
P1ASF = 239; // Row 5 on
P1ASF = 247; // Row 4 on
P1ASF = 251; // Row 3 on
P1ASF = 253; // Row 2 on
P1ASF = 254; // Row 1 on (Bottom row)
```

Additionally:
```c
P1ASF = 1; // This causes every row except the 1st row (bottom) to be lit.
P1ASF = 2; // This causes every row except the 2nd row to be lit.
P1ASF = 3; // This causes every row except the 1st & 2nd row to be lit. You can see this is binary behavior.
...
```

I will try to tweak the firmware so that this works for my board.

**Comment by Sliicy** [comment]
On second thought, I might be frying my LEDs, as they were designed for 3 - 3.2V (they look insanely bright when doing this).
I might need to have P1ASF set to 0xFF, and then manually talk to the pins.

**Comment by Sliicy** [comment]
Upon further investigating, I needed to re-arrange P0, P1, and P2 to be able to light any LED. I was wrong about P1ASF.
In my case:

- P0 controls the Y-Axis
- P1 controls the Z-Axis
- P2 controls the X-Axis.

P0 must be set after P2 and P1 in order for the desired light to take effect.

I was successfully able to get the Java program to display the arrow animation on the cube, as well as other animations, with a few exceptions:
- I had to move the entire framerate function out of Timer0 into a separate void (pixel3), since if it ran in Timer0, it would block the main thread, and block incoming UART/Serial.
 - I am calling this void from the main loop.
 - I essentially disabled Timer0.
 - It seems that the firmware skips every 2nd frame sent over Serial now (I'm using 19200 Baud). Every other baud doesn't work.
 - I even wrote a C# program to talk over serial, and the program without fail keeps drops every 2nd frame, consistently (no matter how fast or slow I send data).

```c
// I'm storing the array as a simple 8x8 (no frame or temp):
__xdata volatile uchar matrix_display[8][8];

// I'm refering to layer as layer_z:
volatile uchar layer_z = 0;   // layer, that is being re-painted
```

Here's the function that's refreshing each frame:
```c
__bit pixel3() {
  if (rx_in > 0) return 1;
  for (uchar y = 0; y < 8; y++) {

      P2 = matrix_display[y][layer_z];

      delay(3);

      // For simplicity, I chose not to use bitwise operators << and >>. I will clean this up in the final release:
      if (layer_z == 0) {
          P1 = 254;
      } else if (layer_z == 1) {
          P1 = 253;
      } else if (layer_z == 2) {
          P1 = 251;
      } else if (layer_z == 3) {
          P1 = 247;
      } else if (layer_z == 4) {
          P1 = 239;
      } else if (layer_z == 5) {
          P1 = 223;
      } else if (layer_z == 6) {
          P1 = 191;
      } else if (layer_z == 7) {
          P1 = 127;
      }

      delay(3);

      if (y == 0) {
        P0 = 127;
      } else if (y == 1) {
        P0 = 191;
      } else if (y == 2) {
        P0 = 223;
      } else if (y == 3) {
        P0 = 239;
      } else if (y == 4) {
        P0 = 247;
      } else if (y == 5) {
        P0 = 251;
      } else if (y == 6) {
        P0 = 253;
      } else if (y == 7) {
        P0 = 254;
      }
      delay(3);

      // Method used to clear away artifacts (Z-Axis "ghost" lines):
      clear_matrix();

  }

  layer_z = (layer_z + 1) % 8; // rewind - ensure we loop in 0-7 layers

  return 0;
}
```

```c
// The function used to wipe the screen back to being empty (otherwise there are artifacts when drawing):
void clear_matrix()
{
  uchar i;
  for (i = 0; i < 8; i++) {
    P2 = 1<<i;
    //P1 = 255; // Seems like clearing P1 isn't needed/doesn't do anything.
    P0 = 255;
  }
}
```

Here's the main loop:
```c
void main()
{
    int value;

    __bit uart_detected = 0;
    __bit frame_started = 0;

    uchar received = 0;

    // init uart - 9600bps@12.000MHz MCU

    // Are these the correct settings for talking over 19200bps@24.000MHz MCU?
    PCON &= 0x7F;       //Baudrate no doubled
    SCON = 0x50;        //8bit and variable baudrate, 1 stop __bit, no parity
    AUXR |= 0x04;       //BRT's clock is Fosc (1T)
    BRT = 0xD9;         //Set BRT's reload value
    AUXR |= 0x01;       //Use BRT as baudrate generator
    AUXR |= 0x10;       //BRT running

    ES = 1;  // enable UART interrupt

    // setup timer0
    TH0 = 0xc0;     // reload value
    TL0 = 0;
    //TR1 = 1;        // timer0 start

    //ET0 = 1; // enable timer0 interrupt
    EA = 1;  // enable global interrupts

    while(1)
    {

      if (uart_detected) // is the cube is being controlled via uart?
        {

          value = read_serial(); // blocks until a byte comes
          if (frame_started == 0)
          {
              if (value == 0xF2) // start receiving batch
              {
                  frame_started = 1; // begin receiving frame data
                  received = 0;        // no rows received
              } else {
                uart_detected = 0; // no more frames coming in
              }
          }
          else
          {
            if (received < 64) {
              matrix_display[received / 8][received % 8] = value;
              received++;
            } else {
              frame_started = 0;
              received = 0;
            }
          }
        } else {
          uart_detected = pixel3();
        }
    }
}
```

The rest of the code remains unchanged.


![image](https://user-images.githubusercontent.com/23116873/127779997-f08c0539-43dd-401b-b6a5-996b7336e191.png)
![IMG_20210801_132353__01](https://user-images.githubusercontent.com/23116873/127780023-26edab61-7aae-41ec-9319-51f95b773df2.jpg)
## Notice how each 2nd frame is dropped:
![LED lighting skipping 2nd frame](https://user-images.githubusercontent.com/23116873/127780395-7e01e209-3d7d-4d6f-89a2-c5d6c573a579.gif)


@tomazas do you know what I'm doing wrong here? Do you know why Timer0 might be choking the rest of the program? I had to get rid of nested loops for performance reasons. So the only issue that remains, is that the cube is dropping every 2nd frame, going dark.

**Comment by Sliicy** [comment]
![Cube working](https://user-images.githubusercontent.com/23116873/127804230-ff5b628b-ac1d-4d30-8504-2f55f08bc0e3.gif)
I got it to fully work! EdKeyes from the Amulius - Embedded Engineering Discord Server helped me figure out why my frame-rate was dropping. I ended up performing a loop from 0 to 62 (since the last frame for whatever reason was ending up in the main loop). If I tried to do a comparison < 64, it would stutter. Doing < 62 solved it for me.

After I clean up my code, I'll share it & perform a pull request.

**Comment by tomazas** [comment]
> * I had to move the entire framerate function out of Timer0 into a separate void (pixel3), since if it ran in Timer0, it would block the main thread, and block incoming UART/Serial.
> * I am calling this void from the main loop.
> * I essentially disabled Timer0.

If you remove the timer and call it directly then you will block the UI which is undesired behavior.

> // I'm storing the array as a simple 8x8 (no frame or temp):
> __xdata volatile uchar matrix_display[8][8];

Without double buffering you will get artifacts - some data will be from one frame and other data from next frame. 
 
>       // For simplicity, I chose not to use bitwise operators << and >>. I will clean this up in the final release:
>       if (layer_z == 0) {
>           P1 = 254;
>       } else if (layer_z == 1) {
>           P1 = 253;
>       } else if (layer_z == 2) {
>           P1 = 251;
>       } else if (layer_z == 3) {
>           P1 = 247;
>       } else if (layer_z == 4) {
>           P1 = 239;
>       } else if (layer_z == 5) {
>           P1 = 223;
>       } else if (layer_z == 6) {
>           P1 = 191;
>       } else if (layer_z == 7) {
>           P1 = 127;
>       }
> 
>       delay(3);
> 
>       if (y == 0) {
>         P0 = 127;
>       } else if (y == 1) {
>         P0 = 191;
>       } else if (y == 2) {
>         P0 = 223;
>       } else if (y == 3) {
>         P0 = 239;
>       } else if (y == 4) {
>         P0 = 247;
>       } else if (y == 5) {
>         P0 = 251;
>       } else if (y == 6) {
>         P0 = 253;
>       } else if (y == 7) {
>         P0 = 254;
>       }
>       delay(3);

This definetely needs optimization to remove branching.

>     // Are these the correct settings for talking over 19200bps@24.000MHz MCU?
>     PCON &= 0x7F;       //Baudrate no doubled
>     SCON = 0x50;        //8bit and variable baudrate, 1 stop __bit, no parity
>     AUXR |= 0x04;       //BRT's clock is Fosc (1T)
>     BRT = 0xD9;         //Set BRT's reload value
>     AUXR |= 0x01;       //Use BRT as baudrate generator
>     AUXR |= 0x10;       //BRT running
> 
>     ES = 1;  // enable UART interrupt
The valid UART code for different baud rates can be generated from the provided STC-ISP program.
